const dictEiwa = {
    "Apple": { search: ["apple"], html: "<p><b>【名詞】</b> …としてのリンゴ、…の形をした果物<br><b>［意味］</b> りんご<br><b>［使用例］</b> I ate a fresh <b>apple</b>.（私は新鮮なりんごを食べた。）</p>" },
    "Book": { search: ["book"], html: "<p><b>【名詞】</b> …に関する本、…の書籍 ／ <b>【動詞】</b> …を予約する、…に書き留める<br><b>［意味］</b> 本、予約する<br><b>［使用例］</b> Read this <b>book</b>.（この本を読みなさい。）</p>" },
    "Dog": { search: ["dog"], html: "<p><b>【名詞】</b> …の種類の犬、…に懐いている犬<br><b>［意味］</b> 犬<br><b>［使用例］</b> He walks his <b>dog</b> every morning.（彼は毎朝犬の散歩をする。）</p>" },
    "Cat": { search: ["cat"], html: "<p><b>【名詞】</b> …の家にいる猫、…に愛されているネコ<br><b>［意味］</b> 猫<br><b>［使用例］</b> The <b>cat</b> is sleeping on the sofa.（猫がソファの上で眠っている。）</p>" },
    "Boy": { search: ["boy"], html: "<p><b>【名詞】</b> …の年齢の男の子、…に属する少年<br><b>［意味］</b> 男の子、少年<br><b>［使用例］</b> The <b>boy</b> runs fast.（その少年は走るのが速い。）</p>" },
    "Girl": { search: ["girl"], html: "<p><b>【名詞】</b> …の制服を着た女の子、…に好かれる少女<br><b>［意味］</b> 女の子、少女<br><b>［使用例］</b> She is a smart <b>girl</b>.（彼女は賢い女の子だ。）</p>" },
    "Teacher": { search: ["teacher"], html: "<p><b>【名詞】</b> …を教える先生、…の学校に勤務する教師<br><b>［意味］</b> 先生、教師<br><b>［使用例］</b> Our English <b>teacher</b> is kind.（私たちの英語の先生は親切だ。）</p>" },
    "Student": { search: ["student"], html: "<p><b>【名詞】</b> …を専攻する学生、…の学級にいる生徒<br><b>［意味］</b> 学生、生徒<br><b>［使用例］</b> I am a high school <b>student</b>.（私は高校生です。）</p>" },
    "School": { search: ["school"], html: "<p><b>【名詞】</b> …の地域にある学校、…に設置された校舎<br><b>［意味］</b> 学校<br><b>［使用例］</b> We go to <b>school</b> by train.（私たちは電車で学校に通っている。）</p>" },
    "Friend": { search: ["friend"], html: "<p><b>【名詞】</b> …にとっての大切な友達、…と親しい友人<br><b>［意味］</b> 友達、友人<br><b>［使用例］</b> He is my best <b>friend</b>.（彼は私の親友です。）</p>" },
    "Family": { search: ["family"], html: "<p><b>【名詞】</b> …の血縁にあたる家族、…と一緒に暮らす世帯<br><b>［意味］</b> 家族<br><b>［使用例］</b> I love my <b>family</b>.（私は家族を愛している。）</p>" },
    "Home": { search: ["home"], html: "<p><b>【名詞】</b> …の安らげる我が家 ／ <b>【副詞】</b> …の自宅へ、…の故郷に<br><b>［意味］</b> 家庭、我が家、家へ<br><b>［使用例］</b> Welcome to my <b>home</b>.（我が家へようこそ。）</p>" },
    "House": { search: ["house"], html: "<p><b>【名詞】</b> …のために建てられた家、…の所有する一軒家<br><b>［意味］</b> 家、家屋<br><b>［使用例］</b> They built a new <b>house</b>.（彼らは新しい家を建てた。）</p>" },
    "Room": { search: ["room"], html: "<p><b>【名詞】</b> …の用途に使う部屋、…に十分なスペース<br><b>［意味］</b> 部屋、空間<br><b>［使用例］</b> Clean your <b>room</b> now.（今すぐ部屋を掃除しなさい。）</p>" },
    "Desk": { search: ["desk"], html: "<p><b>【名詞】</b> …の作業に使う机、…の前に置かれた事務机<br><b>［意味］</b> 机<br><b>［使用例］</b> Put the laptop on the <b>desk</b>.（ノートPCを机の上に置いて。）</p>" },
    "Chair": { search: ["chair"], html: "<p><b>【名詞】</b> …の木で作られた椅子、…の席に座るためのイス<br><b>［意味］</b> 椅子<br><b>［使用例］</b> Please sit on this <b>chair</b>.（どうぞこの椅子に座ってください。）</p>" },
    "Pen": { search: ["pen"], html: "<p><b>【名詞】</b> …のインクが入ったペン、…で文字を書くための筆記具<br><b>［意味］</b> ペン<br><b>［使用例］</b> Sign the paper with a black <b>pen</b>.（黒いペンで書類に署名してください。）</p>" },
    "Pencil": { search: ["pencil"], html: "<p><b>【名詞】</b> …の芯の濃さの鉛筆、…によって削られたペンシル<br><b>［意味］</b> 鉛筆<br><b>［使用例］</b> Can I borrow your <b>pencil</b>?（鉛筆を借りてもいいですか？）</p>" },
    "Notebook": { search: ["notebook"], html: "<p><b>【名詞】</b> …の記録用のノート、…の学習に使う帳面<br><b>［意味］</b> ノート、帳面<br><b>［使用例］</b> Write your ideas in a <b>notebook</b>.（ノートにアイデアを書き留めよう。）</p>" },
    "Clock": { search: ["clock"], html: "<p><b>【名詞】</b> …の壁に掛かっている時計、…の時刻を刻む置き時計<br><b>［意味］</b> 時計（置き時計・掛け時計）<br><b>［使用例］</b> The station <b>clock</b> is accurate.（駅の時計は正確だ。）</p>" },
    "Watch": { search: ["watch"], html: "<p><b>【名詞】</b> …の手首に巻く腕時計 ／ <b>【動詞】</b> …をじっと見る、…を警戒する<br><b>［意味］</b> 腕時計、見る<br><b>［使用例］</b> I <b>watch</b> television after dinner.（私は夕食後にテレビを見る。）</p>" },
    "Bag": { search: ["bag"], html: "<p><b>【名詞】</b> …の荷物を入れる鞄、…の手提げ袋<br><b>［意味］</b> カバン、袋<br><b>［使用例］</b> Pack your clothes into the <b>bag</b>.（服をカバンに詰めなさい。）</p>" },
    "Shoes": { search: ["shoes"], html: "<p><b>【名詞】</b> …の足にぴったり合う靴、…のブランドの履物<br><b>［意味］</b> 靴（複数形）<br><b>［使用例］</b> Take off your <b>shoes</b> here.（ここで靴を脱いでください。）</p>" },
    "Hat": { search: ["hat"], html: "<p><b>【名詞】</b> …の日よけ用の帽子、…の頭に被るハット<br><b>［意味］</b> 帽子（主につばのあるもの）<br><b>［使用例］</b> Wear a <b>hat</b> in the sun.（日差しの中では帽子を被りなさい。）</p>" },
    "Shirt": { search: ["shirt"], html: "<p><b>【名詞】</b> …のサイズの上着シャツ、…の生地のワイシャツ<br><b>［意味］</b> シャツ、ワイシャツ<br><b>［使用例］</b> His white <b>shirt</b> looks clean.（彼の白いシャツは清潔に見える。）</p>" },
    "Coat": { search: ["coat", "コート"], html: "<p><b>【名詞】</b> …の上から羽織るコート、…の外側の防寒着<br><b>［意味］</b> コート、上着<br><b>［使用例］</b> Put on your <b>coat</b> before going out.（出かける前にコートを着なさい。）</p>" },
    "Water": { search: ["water"], html: "<p><b>【名詞】</b> …の成分のコップの水、…に必要な水分<br><b>［意味］</b> 水<br><b>［使用例］</b> Drink plenty of <b>water</b>.（水をたくさん飲みなさい。）</p>" },
    "Milk": { search: ["milk"], html: "<p><b>【名詞】</b> …の牛から絞った牛乳、…に含まれる成分のミルク<br><b>［意味］</b> 牛乳、ミルク<br><b>［使用例］</b> I add <b>milk</b> to my coffee.（私はコーヒーにミルクを入れる。）</p>" },
    "Tea": { search: ["tea"], html: "<p><b>【名詞】</b> …の茶葉から淹れたお茶、…の午後に楽しむ紅茶<br><b>［意味］</b> お茶、紅茶<br><b>［使用例］</b> Would you like a cup of <b>tea</b>?（お茶を一客いかがですか？）</p>" },
    "Coffee": { search: ["coffee"], html: "<p><b>【名詞】</b> …の焙煎されたコーヒー、…の香りがする珈琲<br><b>［意味］</b> コーヒー<br><b>［使用例］</b> Hot <b>coffee</b> wakes me up.（温かいコーヒーで目が覚める。）</p>" },
    "Rice": { search: ["rice"], html: "<p><b>【名詞】</b> …の主食となるお米、…のお皿に盛られたご飯<br><b>［意味］</b> 米、ご飯<br><b>［使用例］</b> Japanese people eat <b>rice</b> daily.（日本人は毎日ご飯を食べる。）</p>" },
    "Bread": { search: ["bread"], html: "<p><b>【名詞】</b> …の小麦粉で焼いたパン、…の朝食に出るブレッド<br><b>［意味］</b> パン<br><b>［使用例］</b> I toast a slice of <b>bread</b>.（私は食パンを1枚トーストする。）</p>" },
    "Cake": { search: ["cake"], html: "<p><b>【名詞】</b> …のお祝いの誕生日ケーキ、…の甘い洋菓子<br><b>［意味］</b> ケーキ<br><b>［使用例］</b> She baked a chocolate <b>cake</b>.（彼女はチョコレートケーキを焼いた。）</p>" },
    "Egg": { search: ["egg"], html: "<p><b>【名詞】</b> …の鳥が産んだ卵、…の料理に使う玉子<br><b>［意味］</b> 卵<br><b>［使用例］</b> Fry an <b>egg</b> for breakfast.（朝食に卵を1個焼きなさい。）</p>" },
    "Fish": { search: ["fish"], html: "<p><b>【名詞】</b> …の水域に生息する魚 ／ <b>【動詞】</b> …の川で魚釣りをする<br><b>［意味］</b> 魚、魚釣りをする<br><b>［使用例］</b> They like to catch <b>fish</b>.（彼らは魚を捕まえるのが好きだ。）</p>" },
    "Meat": { search: ["meat"], html: "<p><b>【名詞】</b> …の動物の食用肉、…の料理のメインの肉<br><b>［意味］</b> 肉<br><b>［使用例］</b> Do you prefer <b>meat</b> or fish?（肉と魚、どちらが好きですか？）</p>" },
    "Orange": { search: ["orange"], html: "<p><b>【名詞】</b> …の柑橘類のオレンジ ／ <b>【形容詞】</b> …のような橙色の<br><b>［意味］</b> オレンジ、橙色<br><b>［使用例］</b> Peel the <b>orange</b> before eating.（食べる前にオレンジの皮をむきなさい。）</p>" },
    "Banana": { search: ["banana"], html: "<p><b>【名詞】</b> …の熱帯で採れるバナナ、…の黄色い果物<br><b>［意味］</b> バナナ<br><b>［使用例］</b> Monkeys love a sweet <b>banana</b>.（サルは甘いバナナが大好きだ。）</p>" },
    "Sun": { search: ["sun"], html: "<p><b>【名詞】</b> …を照らし出す太陽、…の銀河系の中心にある恒星<br><b>［意味］</b> 太陽<br><b>［使用例］</b> The <b>sun</b> rises in the east.（太陽は東から昇る。）</p>" },
    "Moon": { search: ["moon"], html: "<p><b>【名詞】</b> …の夜空に浮かぶ月、…の地球の周りを回る衛星<br><b>［意味］</b> 月<br><b>［使用例］</b> The full <b>moon</b> shines brightly.（満月が明るく輝いている。）</p>" },
    "Star": { search: ["star"], html: "<p><b>【名詞】</b> …にきらめく夜空の星、…の形をしたマーク<br><b>［意味］</b> 星、スター<br><b>［使用例］</b> Look at that bright <b>star</b>.（あの輝く星を見てごらん。）</p>" },
    "Sky": { search: ["sky"], html: "<p><b>【名詞】</b> …の上空に広がる青い空、…の天候を表す大気圏<br><b>［意味］</b> 空、大空<br><b>［使用例］</b> No clouds are in the blue <b>sky</b>.（青空に雲が一つもない。）</p>" },
    "Rain": { search: ["rain"], html: "<p><b>【名詞】</b> …の季節に降る雨 ／ <b>【動詞】</b> …の地域に雨が降る<br><b>［意味］</b> 雨、雨が降る<br><b>［使用例］</b> Heavy <b>rain</b> stopped the game.（激しい雨が試合を中断させた。）</p>" },
    "Snow": { search: ["snow"], html: "<p><b>【名詞】</b> …の冬の白い雪 ／ <b>【動詞】</b> …の山頂に雪が降る<br><b>［意味］</b> 雪、雪が降る<br><b>［使用例］</b> The children play in the <b>snow</b>.（子どもたちは雪の中で遊ぶ。）</p>" },
    "Wind": { search: ["wind"], html: "<p><b>【名詞】</b> …の方向に吹く強い風、…の大気の流れ<br><b>［意味］</b> 風<br><b>［使用例］</b> A cold <b>wind</b> blew all night.（一晩中、冷たい風が吹いた。）</p>" },
    "Sea": { search: ["sea"], html: "<p><b>【名詞】</b> …の広大な青い海、…の波が寄せる沿岸の水域<br><b>［意味］</b> 海<br><b>［使用例］</b> Ships sail across the deep <b>sea</b>.（船が深い海を渡っていく。）</p>" },
    "River": { search: ["river"], html: "<p><b>【名詞】</b> …の渓谷を流れる川、…の海へと続く河川<br><b>［意味］</b> 川、河川<br><b>［使用例］</b> This <b>river</b> flows into the ocean.（この川は海へと流れ込んでいる。）</p>" },
    "Mountain": { search: ["mountain"], html: "<p><b>【名詞】</b> …の標高の高い山、…の連なる山脈<br><b>［意味］</b> 山<br><b>［使用例］</b> Mt. Fuji is a high <b>mountain</b>.（富士山は高い山です。）</p>" },
    "Tree": { search: ["tree"], html: "<p><b>【名詞】</b> …の庭に植えられた一本の木、…のうっそうとした樹木<br><b>［意味］</b> 木、樹木<br><b>［使用例］</b> Apples grow on a <b>tree</b>.（リンゴは木に実る。）</p>" },
    "Flower": { search: ["flower"], html: "<p><b>【名詞】</b> …の季節に咲く美しい花、…の植物の花弁<br><b>［意味］</b> 花<br><b>［使用例］</b> Pick a red <b>flower</b> from the garden.（庭から赤い花を1輪摘みなさい。）</p>" },
    "Bird": { search: ["bird"], html: "<p><b>【名詞】</b> …の大空を羽ばたく鳥、…の種類の野鳥<br><b>［意味］</b> 鳥<br><b>［使用例］</b> A small <b>bird</b> is singing on the branch.（小さな鳥が枝の上でさえずっている。）</p>" },
    "Car": { search: ["car"], html: "<p><b>【名詞】</b> …の所有する自家用車、…の道路を走る自動車<br><b>［意味］</b> 車、自動車<br><b>［使用例］</b> He drives an electric <b>car</b>.（彼は電気自動車を運転する。）</p>" },
    "Train": { search: ["train"], html: "<p><b>【名詞】</b> …の線路を走る電車 ／ <b>【動詞】</b> …の目的のために訓練する<br><b>［意味］</b> 電車、列車、訓練する<br><b>［使用例］</b> The commuter <b>train</b> arrived on time.（通勤電車が時間通りに到着した。）</p>" },
    "Bike": { search: ["bike"], html: "<p><b>【名詞】</b> …の通勤用の自転車、…のエンジンがついたバイク<br><b>［意味］</b> 自転車、バイク<br><b>［使用例］</b> She rides her <b>bike</b> to work.（彼女は自転車で職場に通っている。）</p>" },
    "Bus": { search: ["bus"], html: "<p><b>【名詞】</b> …の停留所に止まる乗合バス、…の大型の車両<br><b>［意味］</b> バス<br><b>［使用例］</b> Wait for the school <b>bus</b> here.（ここでスクールバスを待ち合いなさい。）</p>" },
    "Plane": { search: ["plane"], html: "<p><b>【名詞】</b> …の空港から飛び立つ飛行機、…の上空を飛ぶ機体<br><b>［意味］</b> 飛行機<br><b>［使用例］</b> The <b>plane</b> flew above the clouds.（飛行機は雲の上を飛んだ。）</p>" },
    "Station": { search: ["station"], html: "<p><b>【名詞】</b> …の路線の鉄道の駅、…に設置された停留所<br><b>［意味］</b> 駅<br><b>［使用例］</b> Meet me at the subway <b>station</b>.（地下鉄の駅で待ち合わせよう。）</p>" },
    "Park": { search: ["park"], html: "<p><b>【名詞】</b> …の市民が集う憩いの公園 ／ <b>【動詞】</b> …の駐車場に車を停める<br><b>［意味］</b> 公園、駐車する<br><b>［使用例］</b> Children are playing in the <b>park</b>.（子どもたちが公園で遊んでいる。）</p>" },
    "Good": { search: ["good"], html: "<p><b>【形容詞】</b> …にとって品質が良い、…の能力が優れている<br><b>［意味］</b> 良い、優れた<br><b>［使用例］</b> Have a <b>good</b> day!（良い一日を！）</p>" },
    "Happy": { search: ["happy"], html: "<p><b>【形容詞】</b> …の出来事で幸せな、…に対して非常に嬉しい<br><b>［意味］</b> 幸せな、うれしい<br><b>［使用例］</b> They are a <b>happy</b> couple.（彼らは幸せな夫婦だ。）</p>" },
    "Airport": { search: ["airport"], html: "<p><b>【名詞】</b> …の国際線がある空港、…の飛行機が発着する場所<br><b>［意味］</b> 空港<br><b>［使用例］</b> The taxi took us to the <b>airport</b>.（タクシーが私たちを空港へ連れて行った。）</p>" },
    "Secret": { search: ["secret"], html: "<p><b>【名詞】</b> …の他人に隠している秘密 ／ <b>【形容詞】</b> …の非公開の<br><b>［意味］</b> 秘密、秘密の<br><b>［使用例］</b> Keep this password a <b>secret</b>.（このパスワードは秘密にしておきなさい。）</p>" },
    "Promise": { search: ["promise"], html: "<p><b>【名詞】</b> …との間で交わした約束 ／ <b>【動詞】</b> …することを約束する<br><b>［意味］</b> 約束、約束する<br><b>［使用例］</b> Don't break your <b>promise</b>.（約束を破ってはいけない。）</p>" },
    "Newspaper": { search: ["newspaper"], html: "<p><b>【名詞】</b> …の朝に配達される新聞、…の情報が載ったニュース紙<br><b>［意味］</b> 新聞<br><b>［使用例］</b> My father reads the <b>newspaper</b> every morning.（父は毎朝新聞を読む。）</p>" },
    "Diary": { search: ["diary"], html: "<p><b>【名詞】</b> …の毎日の出来事を書く日記、…を記録する手帳<br><b>［意味］</b> 日記<br><b>［使用例］</b> She writes in her <b>diary</b> before bed.（彼女は寝る前に日記を書く。）</p>" },
    "System": { search: ["system"], html: "<p><b>【名詞】</b> …の管理のためのシステム、…の連動した組織構造<br><b>［意味］</b> システム、制度、組織<br><b>［使用例］</b> The computer <b>system</b> is down.（コンピュータシステムが停止している。）</p>" },
    "Space": { search: ["space"], html: "<p><b>【名詞】</b> …の星が浮かぶ宇宙空間、…のための空いている場所<br><b>［意味］</b> 宇宙、空間、スペース<br><b>［使用例］</b> Rockets travel into deep <b>space</b>.（ロケットは深宇宙へと旅立つ。）</p>" },
    "Earth": { search: ["earth"], html: "<p><b>【名詞】</b> …の生命が生きる地球、…の植物を育てるための土壌<br><b>［意味］</b> 地球、大国、土<br><b>［使用例］</b> Protecting the <b>Earth</b> is important.（地球を守ることは重要だ。）</p>" },
    "World": { search: ["world"], html: "<p><b>【名詞】</b> …の全人類が住む世界、…の特定の分野の社会<br><b>［意味］</b> 世界<br><b>［使用例］</b> English is spoken around the <b>world</b>.（英語は世界中で話されている。）</p>" },
    "History": { search: ["history"], html: "<p><b>【名詞】</b> …の国が歩んできた歴史、…の過去の古い記録<br><b>［意味］</b> 歴史<br><b>［使用例］</b> I like learning ancient <b>history</b>.（私は古代史を学ぶのが好きだ。）</p>" },
    "Tool": { search: ["tool"], html: "<p><b>【名詞】</b> …の作業を効率的にする道具、…を達成するための手段<br><b>［意味］</b> 道具、工具<br><b>［使用例］</b> A hammer is a useful <b>tool</b>.（ハンマーは便利な道具だ。）</p>" },
    "Machine": { search: ["machine"], html: "<p><b>【名詞】</b> …の工場で動いている機械、…の自動の装置<br><b>［意味］</b> 機械<br><b>［使用例］</b> This washing <b>machine</b> saves energy.（この洗濯機は節電になる。）</p>" },
    "Clothes": { search: ["clothes"], html: "<p><b>【名詞】</b> …の季節に合わせた衣服、…の身にまとう衣類全般<br><b>［意味］</b> 服、衣服（常に複数扱い）<br><b>［使用例］</b> Change your wet <b>clothes</b>.（濡れた服を着替えなさい。）</p>" },
    "Socks": { search: ["socks"], html: "<p><b>【名詞】</b> …の足の寒さを防ぐ靴下、…のペアのソックス<br><b>［意味］</b> 靴下（複数形）<br><b>［使用例］</b> My <b>socks</b> have holes in them.（私の靴下に穴が開いている。）</p>" },
    "Glasses": { search: ["glasses"], html: "<p><b>【名詞】</b> …の視力を矯正するための眼鏡、…のレンズがついたメガネ<br><b>［意味］</b> メガネ（複数形）<br><b>［使用例］</b> I wear <b>glasses</b> for reading.（私は読書用のメガネをかけている。）</p>" },
    "Bedding": { search: ["bedding"], html: "<p><b>【名詞】</b> …の寝室に敷く布団、…の快適な睡眠のための寝具<br><b>［意味］</b> 寝具、布団一式<br><b>［使用例］</b> Wash the <b>bedding</b> on sunny days.（晴れた日に寝具を洗いなさい。）</p>" },
    "Soap": { search: ["soap"], html: "<p><b>【名詞】</b> …の皮膚を綺麗にする石鹸、…の汚れを落とす固形石けん<br><b>［意味］</b> 石鹸<br><b>［使用例］</b> Wash your hands with <b>soap</b>.（石鹸で手を洗いなさい。）</p>" },
    "Toy": { search: ["toy"], html: "<p><b>【名詞】</b> …の子どもが夢中で遊ぶ玩具、…の形を模したおもちゃ<br><b>［意味］</b> おもちゃ、玩具<br><b>［使用例］</b> Put away your <b>toy</b> box.（おもちゃ箱を片付けなさい。）</p>" },
    "Keyhole": { search: ["keyhole"], html: "<p><b>【名詞】</b> …の扉の鍵を差し込む鍵穴、…の小さなスリット<br><b>［意味］</b> 鍵穴<br><b>［使用例］</b> Peer through the old <b>keyhole</b>.（古い鍵穴からのぞき見なさい。）</p>" },
    "Blackboard": { search: ["blackboard"], html: "<p><b>【名詞】</b> …の学校の教室にある黒板、…のチョークで書く板<br><b>［意味］</b> 黒板<br><b>［使用例］</b> Copy the notes from the <b>blackboard</b>.（黒板からノートを写しなさい。）</p>" },
    "Map": { search: ["map"], html: "<p><b>【名詞】</b> …の土地の位置を示した地図、…の全体の案内図<br><b>［意味］</b> 地図<br><b>［使用例］</b> Follow the route on the <b>map</b>.（地図上のルートをたどりなさい。）</p>" },
    "Letter": { search: ["letter"], html: "<p><b>【名詞】</b> …の相手に思いを届ける手紙、…のアルファベットの文字<br><b>［意味］</b> 手紙、文字<br><b>［使用例］</b> I received an anonymous <b>letter</b>.（私は匿名の They 手紙を受け取った。）</p>" },
    "Photo": { search: ["photo"], html: "<p><b>【名詞】</b> …の旅の思い出を記録した写真、…のカメラで写した画像<br><b>［意味］</b> 写真<br><b>［使用例］</b> Take a <b>photo</b> of this castle.（このお城の写真を撮りなさい。）</p>" },
    "Dresser": { search: ["dresser"], html: "<p><b>【名詞】</b> …の寝室に置いてある鏡台、…の化粧をするための家具<br><b>［意味］</b> 鏡台、化粧台、衣装だんす<br><b>［使用例］</b> Store your socks in the <b>dresser</b>.（靴下を鏡台の引き出しにしまいなさい。）</p>" },
    "Ring": { search: ["ring"], html: "<p><b>【名詞】</b> …の指にはめる貴金属の指輪、…の形をした円形の輪<br><b>［意味］</b> 指輪、輪<br><b>［使用例］</b> She wore a gold <b>ring</b>.（彼女は金の指輪をはめていた。）</p>" },
    "Wallet": { search: ["wallet"], html: "<p><b>【名詞】</b> …のお金やカードを入れる財布、…の紛失防止つきの革財布<br><b>［意味］</b> 財布<br><b>［使用例］</b> I left my <b>wallet</b> at home.（私は家に財布を忘れた。）</p>" },
    "Umbrella": { search: ["umbrella"], html: "<p><b>【名詞】</b> …の雨の日用の傘、…の強い日差しを遮る日傘<br><b>［意味］</b> 傘<br><b>［使用例］</b> Open your <b>umbrella</b>; it's raining.（雨が降っているから傘を開きなさい。）</p>" },
    "Notebook": { search: ["notebook"], html: "<p><b>【名詞】</b> …のスケジュール管理用の手帳、…の小型のメモ帳<br><b>［意味］</b> 手帳、ノート<br><b>［使用例］</b> Check your appointment in the <b>notebook</b>.（手帳で予定を確認しなさい。）</p>" },
    "Paint": { search: ["paint"], html: "<p><b>【名詞】</b> …の絵を描くための絵の具 ／ <b>【動詞】</b> …の壁に色を塗る<br><b>［意味］</b> 絵の具、ペンキ、塗る<br><b>［使用例］</b> The artist mixed the <b>paint</b>.（画家は絵の具を混ぜ合わせた。）</p>" },
    "Scissors": { search: ["scissors"], html: "<p><b>【名詞】</b> …の紙を綺麗に切り取る鋏、…の刃が交差したハサミ<br><b>［意味］</b> ハサミ（複数形）<br><b>［使用例］</b> Cut the thread with <b>scissors</b>.（ハサミで糸を切りなさい。）</p>" },
    "Ruler": { search: ["ruler"], html: "<p><b>【名詞】</b> …の直線を引くための定規、…の地域を治める支配者<br><b>［意味］</b> 定規、支配者<br><b>［使用例］</b> Measure the length with a <b>ruler</b>.（定規で長さを測りなさい。）</p>" },
    "Globe": { search: ["globe"], html: "<p><b>【名詞】</b> …の地球の姿を模した地球儀、…の天体としての地球そのもの<br><b>［意味］</b> 地球儀、地球、球体<br><b>［使用例］</b> He spun the <b>globe</b> with his finger.（彼は地球儀を指で回した。）</p>" },
    "Balloon": { search: ["balloon"], html: "<p><b>【名詞】</b> …の空기에浮かぶ丸い風船、…の大型の気球<br><b>［意味］</b> 風船<br><b>［使用例］</b> The red <b>balloon</b> floated away.（赤い風船が飛んでいってしまった。）</p>" },
    "Doll": { search: ["doll"], html: "<p><b>【名詞】</b> …の人間の姿にそっくりな人形、…の可愛らしいフィギュア<br><b>［意味］</b> 人形<br><b>［使用例］</b> She treats the <b>doll</b> like a baby.（彼女はその人形を赤このように扱っている。）</p>" },
    "Staircase": { search: ["staircase"], html: "<p><b>【名詞】</b> …の建物の内部にある階段室、…の一連のつながった階段構造<br><b>［意味］</b> 階段（構造物としての階段全体）<br><b>［使用例］</b> Walk down the spiral <b>staircase</b>.（らせん階段を降りなさい。）</p>" },
    "Bulb": { search: ["bulb"], html: "<p><b>【名詞】</b> …の部屋を明るく照らす電球、…の植物の球根<br><b>［意味］</b> 電球、球根<br><b>［使用例］</b> Replace the broken light <b>bulb</b>.（切れた電球を交換しなさい。）</p>" },
    "Sidewalk": { search: ["sidewalk"], html: "<p><b>【名詞】</b> …の歩行者が安全に通るための歩道、…の舗装された通路<br><b>［意味］</b> 歩道<br><b>［使用例］</b> Pedestrians must use the <b>sidewalk</b>.（歩行者は歩道を歩かなければならない。）</p>" },
    "Roadway": { search: ["roadway"], html: "<p><b>【名詞】</b> …の自動車が高速で行き交う車道、…の車両専用の道路<br><b>［意味］</b> 車道、道路<br><b>［使用例］</b> Cars are driving on the <b>roadway</b>.（車が車道を走っている。）</p>" },
    "Kitchen": { search: ["kitchen"], html: "<p><b>【名詞】</b> …の美味しい料理を作る台所、…に設置されたシステムキッチン<br><b>［意味］</b> 台所、キッチン<br><b>［使用例］</b> Delicious smells came from the <b>kitchen</b>.（台所から美味しそうな匂いがしてきた。）</p>" },
    "Window": { search: ["window"], html: "<p><b>【名詞】</b> …の光を取り込むための窓、…の役所の受付窓口<br><b>［意味］</b> 窓、ウィンドウ<br><b>［使用例］</b> Open the <b>window</b> for fresh air.（新鮮な空気を入れるために窓を開けなさい。）</p>" }
};