const dictEiwa = {
    // === 日本語単語：英語に直すと？（和英60個） ===
    "東京": "<p><b>英訳:</b> Tokyo</p><p><b>用例:</b> I live in Tokyo.（私は東京に住んでいます。）</p>",
    "学校": "<p><b>英訳:</b> school</p><p><b>用例:</b> I go to school every day.（私は毎日学校に行きます。）</p>",
    "先生": "<p><b>英訳:</b> teacher</p><p><b>用例:</b> She is a good teacher.（彼女は良い先生です。）</p>",
    "友達": "<p><b>英訳:</b> friend</p><p><b>用例:</b> He is my best friend.（彼は私の親友です。）</p>",
    "家族": "<p><b>英訳:</b> family</p><p><b>用例:</b> I love my family.（私は家族が大好きです。）</p>",
    "勉強": "<p><b>英訳:</b> study</p><p><b>用例:</b> I study English every night.（私は毎晩英語を勉強します。）</p>",
    "英語": "<p><b>英訳:</b> English</p><p><b>用例:</b> English is very fun.（英語はとても楽しいです。）</p>",
    "日本語": "<p><b>英訳:</b> Japanese</p><p><b>用例:</b> Speak in Japanese, please.（日本語で話してください。）</p>",
    "本棚": "<p><b>英訳:</b> bookshelf</p><p><b>用例:</b> Put the book on the bookshelf.（本を本棚に戻しなさい。）</p>",
    "教室": "<p><b>英訳:</b> classroom</p><p><b>用例:</b> Our classroom is clean.（私たちの教室はきれいです。）</p>",
    "時計": "<p><b>英訳:</b> clock</p><p><b>用例:</b> Look at the wall clock.（壁の時計を見なさい。）</p>",
    "電話": "<p><b>英訳:</b> phone</p><p><b>用例:</b> My phone is on the desk.（私の電話は机の上にあります。）</p>",
    "電車": "<p><b>英訳:</b> train</p><p><b>用例:</b> The train is coming now.（今、電車が来るところです。）</p>",
    "自転車": "<p><b>英訳:</b> bike</p><p><b>用例:</b> I ride my bike to school.（私は自転車で学校に通っています。）</p>",
    "車掌": "<p><b>英訳:</b> conductor</p><p><b>用例:</b> The conductor checked my ticket.（車掌さんが私の切符を確認した。）</p>",
    "駅員": "<p><b>英訳:</b> station staff</p><p><b>用例:</b> Ask the station staff for help.（駅員さんに助けてもらいなさい。）</p>",
    "交番": "<p><b>英訳:</b> police box</p><p><b>用例:</b> There is a police box near the station.（駅の近くに交番があります。）</p>",
    "病院": "<p><b>英訳:</b> hospital</p><p><b>用例:</b> Go to the hospital if you are sick.（病気なら病院に行きなさい。）</p>",
    "薬局": "<p><b>英訳:</b> pharmacy</p><p><b>用例:</b> Buy some medicine at the pharmacy.（薬局で薬を買いなさい。）</p>",
    "公園": "<p><b>英訳:</b> park</p><p><b>用例:</b> Let's play in the park.（公園で遊ぼう。）</p>",
    "動物園": "<p><b>英訳:</b> zoo</p><p><b>用例:</b> We saw monkeys at the zoo.（私たちは動物園でサルを見ました。）</p>",
    "図書館": "<p><b>英訳:</b> library</p><p><b>用例:</b> I borrow books from the library.（私は図書館から本を借ります。）</p>",
    "映画館": "<p><b>英訳:</b> movie theater</p><p><b>用例:</b> I go to the movie theater on Sundays.（私は日曜日に映画館に行きます。）</p>",
    "銀行": "<p><b>英訳:</b> bank</p><p><b>用例:</b> The bank opens at nine.（銀行は9時に開きます。）</p>",
    "郵便局": "<p><b>英訳:</b> post office</p><p><b>用例:</b> Where is the post office?（郵便局はどこですか？）</p>",
    "商店街": "<p><b>英訳:</b> shopping street</p><p><b>用例:</b> This shopping street is always busy.（この商店街はいつも賑やかだ。）</p>",
    "料理": "<p><b>英訳:</b> cooking</p><p><b>用例:</b> My hobby is cooking.（私の趣味は料理です。）</p>",
    "食堂": "<p><b>英訳:</b> cafeteria</p><p><b>用例:</b> Eat lunch at the school cafeteria.（学校の食堂でお昼を食べなさい。）</p>",
    "朝御飯": "<p><b>英訳:</b> breakfast</p><p><b>用例:</b> I eat breakfast at seven.（私は7時に朝御飯を食べます。）</p>",
    "昼御飯": "<p><b>英訳:</b> lunch</p><p><b>用例:</b> Make a lunch box for me.（お弁当［昼御飯］を作って。）</p>",
    "晩御飯": "<p><b>英訳:</b> dinner</p><p><b>用例:</b> What is for dinner tonight?（今夜の晩御飯は何？）</p>",
    "お茶": "<p><b>英訳:</b> green tea</p><p><b>用例:</b> Drink hot green tea.（温かいお茶を飲みなさい。）</p>",
    "水筒": "<p><b>英訳:</b> water bottle</p><p><b>用例:</b> Don't forget your water bottle.（水筒を忘れないでね。）</p>",
    "音楽": "<p><b>英訳:</b> music</p><p><b>用例:</b> I like listening to music.（私は音楽を聴くのが好きです。）</p>",
    "楽器": "<p><b>英訳:</b> musical instrument</p><p><b>用例:</b> Can you play any musical instrument?（何か楽器は弾けますか？）</p>",
    "歌唱": "<p><b>英訳:</b> singing</p><p><b>用例:</b> Her singing is very beautiful.（彼女の歌唱はとても美しい。）</p>",
    "絵画": "<p><b>英訳:</b> painting</p><p><b>用例:</b> Look at this beautiful painting.（この美しい絵画を見なさい。）</p>",
    "筆箱": "<p><b>英訳:</b> pencil case</p><p><b>用例:</b> My pencil case is blue.（私の筆箱は青色です。）</p>",
    "消しゴム": "<p><b>英訳:</b> eraser</p><p><b>用例:</b> Lend me your eraser, please.（消しゴムを貸してください。）</p>",
    "宿題": "<p><b>英訳:</b> homework</p><p><b>用例:</b> Do your homework before dinner.（晩御飯の前に宿題をしなさい。）</p>",
    "試験": "<p><b>英訳:</b> test</p><p><b>用例:</b> We have a math test tomorrow.（明日は数学の試験があります。）</p>",
    "運動": "<p><b>英訳:</b> exercise</p><p><b>用例:</b> Running is a good exercise.（走ることは良い運動です。）</p>",
    "野球": "<p><b>英訳:</b> baseball</p><p><b>用例:</b> Let's play baseball after school.（放課後に野球をしよう。）</p>",
    "庭球": "<p><b>英訳:</b> tennis</p><p><b>用例:</b> She plays tennis very well.（彼女はテニスがとても上手です。）</p>",
    "籠球": "<p><b>英訳:</b> basketball</p><p><b>用例:</b> He runs fast during basketball games.（彼は籠球の試合中、速く走る。）</p>",
    "排球": "<p><b>英訳:</b> volleyball</p><p><b>用例:</b> Volleyball is a team sport.（排球はチームスポーツです。）</p>",
    "蹴球": "<p><b>英訳:</b> soccer</p><p><b>用例:</b> Soccer is popular all over the world.（蹴球は世界中で人気です。）</p>",
    "水泳": "<p><b>英訳:</b> swimming</p><p><b>用例:</b> Swimming in the pool is fun.（プールでの水泳は楽しい。）</p>",
    "階段": "<p><b>英訳:</b> stairs</p><p><b>用例:</b> Walk up the stairs slowly.（階段をゆっくり上りなさい。）</p>",
    "窓口": "<p><b>英訳:</b> window / counter</p><p><b>用例:</b> Go to the ticket window.（切符の窓口に行きなさい。）</p>",
    "切符": "<p><b>英訳:</b> ticket</p><p><b>用例:</b> Buy a train ticket first.（最初に電車の切符を買いなさい。）</p>",
    "改札": "<p><b>英訳:</b> ticket gate</p><p><b>用例:</b> Touch your card at the ticket gate.（改札でカードをタッチしてね。）</p>",
    "天気": "<p><b>英訳:</b> weather</p><p><b>用例:</b> How is the weather today?（今日の天気はどうですか？）</p>",
    "太陽": "<p><b>英訳:</b> sun</p><p><b>用例:</b> The sun is very bright.（太陽がとてもまぶしい。）</p>",
    "向日葵": "<p><b>英訳:</b> sunflower</p><p><b>用例:</b> Sunflowers bloom in summer.（向日葵は夏に咲きます。）</p>",
    "桜花": "<p><b>英訳:</b> cherry blossom</p><p><b>用例:</b> Cherry blossoms are beautiful.（桜花は美しいです。）</p>",
    "紅葉": "<p><b>英訳:</b> autumn leaves</p><p><b>用例:</b> Look at the red autumn leaves.（赤い紅葉を見なさい。）</p>",
    "富士山": "<p><b>英訳:</b> Mt. Fuji</p><p><b>用例:</b> Mt. Fuji is the highest mountain in Japan.（富士山は日本で一番高い山です。）</p>",
    "新幹線": "<p><b>英訳:</b> bullet train</p><p><b>用例:</b> We took the bullet train to Kyoto.（私たちは京都まで新幹線に乗りました。）</p>",
    "お土産": "<p><b>英訳:</b> souvenir</p><p><b>用例:</b> I bought this souvenir for you.（あなたにお土産を買ってきました。）</p>",

    // === 英語単語：日本語に直すと？（英和60個） ===
    "Apple": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> リンゴ</p><p><b>用例:</b> I eat an apple every morning.（私は毎朝リンゴを食べます。）</p>",
    "Book": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 本、書籍</p><p><b>用例:</b> Read this book.（この本を読みなさい。）</p>",
    "Dog": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 犬（いぬ）</p><p><b>用例:</b> I walk my dog every day.（私は毎日犬の散歩をします。）</p>",
    "Cat": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 猫（ねこ）</p><p><b>用例:</b> The cat is sleeping on the chair.（猫が椅子の上で寝ています。）</p>",
    "Boy": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 男の子、少年</p><p><b>用例:</b> He is a kind boy.（彼は親切な男の子です。）</p>",
    "Girl": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 女の子、少女</p><p><b>用例:</b> The girl is drawing a picture.（その女の子は絵を描いています。）</p>",
    "Teacher": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 先生、教師</p><p><b>用例:</b> Ask your teacher a question.（先生に質問しなさい。）</p>",
    "Student": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 生徒、学生</p><p><b>用例:</b> I am a junior high school student.（私は中学生です。）</p>",
    "School": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 学校</p><p><b>用例:</b> Walk to school with friends.（友達と一緒に学校へ歩きなさい。）</p>",
    "Friend": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 友達、友人</p><p><b>用例:</b> Make many friends here.（ここでたくさんの友達を作りなさい。）</p>",
    "Family": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 家族</p><p><b>用例:</b> My family is big.（私の家族は大きいです［大家族です］。）</p>",
    "Home": "<p><b>品詞:</b> 【名詞】【副詞】</p><p><b>和訳:</b> お家、我が家 ／ お家へ</p><p><b>用例:</b> Go home early today.（今日は早くお家に帰りなさい。）</p>",
    "House": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 家、建物</p><p><b>用例:</b> They live in a white house.（彼らは白い家に住んでいます。）</p>",
    "Room": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 部屋、室</p><p><b>用例:</b> Clean your room now.（今すぐ部屋を掃除しなさい。）</p>",
    "Desk": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 机（つくえ）</p><p><b>用例:</b> Put your notebook on the desk.（ノートを机の上に置きなさい。）</p>",
    "Chair": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 椅子（いす）</p><p><b>用例:</b> Sit on this chair, please.（この椅子に座ってください。）</p>",
    "Pen": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> ペン</p><p><b>用例:</b> Write with a black pen.（黒いペンで書きなさい。）</p>",
    "Pencil": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 鉛筆（えんぴつ）</p><p><b>用例:</b> Use a pencil to draw lines.（線を引くのに鉛筆を使いなさい。）</p>",
    "Notebook": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> ノート、手帳</p><p><b>用例:</b> Open your notebook to page five.（ノートの5ページを開きなさい。）</p>",
    "Clock": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 時計（かけ時計など）</p><p><b>用例:</b> The clock stopped at ten.（時計が10時で止まりました。）</p>",
    "Watch": "<p><b>品詞:</b> 【名詞】【動詞】</p><p><b>和訳:</b> 腕時計 ／ 〜をじっと見る</p><p><b>用例:</b> Watch TV for an hour.（テレビを1時間見なさい。）</p>",
    "Bag": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> カバン、袋</p><p><b>用例:</b> Put the text in your bag.（テキストをカバンに入れなさい。）</p>",
    "Shoes": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 靴（くつ）</p><p><b>用例:</b> Wash your shoes on Saturdays.（土曜日に靴を洗いなさい。）</p>",
    "Hat": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 帽子（ふちのあるもの）</p><p><b>用例:</b> Wear a hat on sunny days.（晴れた日は帽子をかぶりなさい。）</p>",
    "Shirt": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> シャツ</p><p><b>用例:</b> This white shirt is cheap.（この白いシャツは安いです。）</p>",
    "Coat": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> コート、上着</p><p><b>用例:</b> Put on your coat. It is cold.（コートを着なさい。寒いですよ。）</p>",
    "Water": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 水（みず）</p><p><b>用例:</b> Drink a glass of water.（コップ一杯の水を飲みなさい。）</p>",
    "Milk": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 牛乳、ミルク</p><p><b>用例:</b> Milk is good for your teeth.（牛乳は歯に良いです。）</p>",
    "Tea": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> お茶、紅茶</p><p><b>用例:</b> Do you want hot tea?（温かいお茶はいかがですか？）</p>",
    "Coffee": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> コーヒー</p><p><b>用例:</b> My father drinks coffee.（父はコーヒーを飲みます。）</p>",
    "Rice": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> ごはん、お米</p><p><b>用例:</b> We eat rice for breakfast.（私たちは朝御飯に白米を食べます。）</p>",
    "Bread": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> パン</p><p><b>用例:</b> I prefer bread to rice.（私はお米よりパンが好きです。）</p>",
    "Cake": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> ケーキ</p><p><b>用例:</b> Cut the birthday cake.（誕生日ケーキを切りなさい。）</p>",
    "Egg": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 卵（たまご）</p><p><b>用例:</b> Cook an egg for me.（卵を料理して［焼いて］ください。）</p>",
    "Fish": "<p><b>品詞:</b> 【名詞】【動詞】</p><p><b>和訳:</b> 魚（さかな） ／ 魚釣りをする</p><p><b>用例:</b> He can catch a big fish.（彼は大きな魚を捕まえることができます。）</p>",
    "Meat": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> お肉</p><p><b>用例:</b> Don't eat too much meat.（お肉をたくさん食べすぎないで。）</p>",
    "Orange": "<p><b>品詞:</b> 【名詞】【形容詞】</p><p><b>和訳:</b> オレンジ ／ オレンジ色の</p><p><b>用例:</b> I like fresh orange juice.（私は生のオレンジジュースが好きです。）</p>",
    "Banana": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> バナナ</p><p><b>用例:</b> Peel a banana carefully.（バナナの皮を注意深くむきなさい。）</p>",
    "Sun": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 太陽、ひなた</p><p><b>用例:</b> The sun rises in the east.（太陽は東から昇ります。）</p>",
    "Moon": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 月（つき）</p><p><b>用例:</b> The moon is beautiful tonight.（今夜は月が綺麗ですね。）</p>",
    "Star": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 星（ほし）、スター</p><p><b>用例:</b> We can see a bright star.（輝く星が見えます。）</p>",
    "Sky": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 空（そら）</p><p><b>用例:</b> The blue sky looks wide.（青い空が広く見えます。）</p>",
    "Rain": "<p><b>品詞:</b> 【名詞】【動詞】</p><p><b>和訳:</b> 雨 ／ 雨が降る</p><p><b>用例:</b> It started to rain heavy.（雨が激しく降り始めました。）</p>",
    "Snow": "<p><b>品詞:</b> 【名詞】【動詞】</p><p><b>和訳:</b> 雪（ゆき） ／ 雪が降る</p><p><b>用例:</b> Children love white snow.（子供たちは白い雪が大好物です。）</p>",
    "Wind": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 風（かぜ）</p><p><b>用例:</b> A strong wind is blowing.（強い風が吹いています。）</p>",
    "Sea": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 海（うみ）</p><p><b>用例:</b> Swim in the blue sea.（青い海で泳ぎなさい。）</p>",
    "River": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 川（かわ）</p><p><b>用例:</b> This river flows fast.（この川は流れが速いです。）</p>",
    "Mountain": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 山（やま）</p><p><b>用例:</b> Climb the mountain with him.（彼と一緒に山を登りなさい。）</p>",
    "Tree": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 木、樹木</p><p><b>用例:</b> There is a big tree here.（ここに大きな木があります。）</p>",
    "Flower": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 花（はな）</p><p><b>用例:</b> Give a red flower to her.（彼女に赤い花をあげなさい。）</p>",
    "Bird": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 鳥（とり）</p><p><b>用例:</b> A small bird is singing.（小さな鳥が歌っています。）</p>",
    "Car": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 車、自動車</p><p><b>用例:</b> Drive your new car slow.（新しい車をゆっくり運転しなさい。）</p>",
    "Train": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 電車、列車</p><p><b>用例:</b> Don't miss the last train.（最終電車に乗り遅れないで。）</p>",
    "Bike": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 自転車、バイク</p><p><b>用例:</b> My bike has a flat tire.（私の自転車はパンクしています。）</p>",
    "Bus": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> バス</p><p><b>用例:</b> Wait for the next school bus.（次のスクールバスを待ちなさい。）</p>",
    "Plane": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 飛行機</p><p><b>用例:</b> The plane flew over the hill.（飛行機が丘の上を飛んでいきました。）</p>",
    "Station": "<p><b>品詞:</b> 【名詞】</p><p><b>和訳:</b> 駅（えき）</p><p><b>用例:</b> Meet me at the train station.（電車の駅で待ち合わせしましょう。）</p>",
    "Park": "<p><b>品詞:</b> 【名詞】【動詞】</p><p><b>和訳:</b> 公園 ／ 車を駐車する</p><p><b>用例:</b> Park your car right here.（ここに車を止めなさい。）</p>"
};